---
version: '2.3'

x-service: &default-service
  restart: 'unless-stopped'
  logging:
    driver: 'json-file'
    options:
      max-size: "${LOGGING_MAX_SIZE}"
      max-file: "${LOGGING_MAX_FILE}"

services:

  rundeck:
    <<: *default-service
    image: "${RUNDECK_IMAGE_NAME}:${RUNDECK_IMAGE_VERSION}"
    container_name: rundeck
    hostname: rundeck
    # depends_on:
    #   db:
    #     condition: service_healthy
    ports:
      - "${RUNDECK_PORT}:4440"
    labels:
      - "stack=rundeck"
      - "application=rundeck"
    env_file:
      - 'env/rundeck.env'
    volumes:
      - './keys/dawan:/home/rundeck/.ssh/dawan'
      - './config/:/home/rundeck/ressources-yaml'
    networks:
      rundeck-dawan-fr:
        ipv4_address: ${RUNDECK_IPV4_NETWORK:-10.0.0}.11

  # db:
  #   <<: *default-service
  #   image: ${DB_IMAGE_NAME}:${DB_IMAGE_VERSION}
  #   hostname: rundeck-database
  #   container_name: rundeck_database
  #   labels:
  #     - "stack=vault"
  #     - "application=mysql"
  #   healthcheck:
  #     test: >-
  #         mysqladmin ping \
  #           --user=$${MYSQL_USER} \
  #           --password=$${MYSQL_PASSWORD} \
  #           --host db
  #     timeout: 10s
  #     retries: 10
  #     interval: 5s
  #   env_file:
  #     - 'env/db.env'
  #   volumes:
  #     - rundeck-db:/var/lib/mysql:rw
  #   networks:
  #     rundeck-dawan-fr:
  #       ipv4_address: ${RUNDECK_IPV4_NETWORK:-10.0.0}.10

volumes:
  rundeck-db:
    driver: local

networks:
  rundeck-dawan-fr:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-rundeck
    ipam:
      driver: default
      config:
        - subnet: ${RUNDECK_IPV4_NETWORK:-10.0.0}.8/${RUNDECK_CIDR:-29}
